dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export BOTO_CONFIG=/dev/null
  - pip freeze
  - pytest --cov
  - codecov
